export enum GameState {
  GAME_IN_PROGRESS = "GAME_IN_PROGRESS",
  GAME_OVER = "GAME_OVER",
  WAITING_TO_START = "WAITING_TO_START",
  FILLING_NUMBERS = "FILLING_NUMBERS",
  FILLED_NUMBERS = "FILLED_NUMBERS",
  MATCH_OVER = "MATCH_OVER",
}
